### ISSUE TITLE
Avoid repetition of macros and parameters

### ISSUE THREAD

**Issue by FreshMag** [FreshMag/subjekt#18]
Would be nice to be able to import global macros and parameters from other suites, for example:

```yaml
config: ...
import:
   - "./otherSuite.yaml"
   - ...
subjects: ...
```
